# .goreleaser.yml

before:
  hooks:
    - go mod download

builds:
  - goos: linux
    goarch: amd64

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: owner-name
    name: repo-name
    token: $GITHUB_TOKEN
    draft: true
    release_name: {{.Tag}}
    file_glob: true
    file: dist/*
