name: Release on Merge

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Run goreleaser
        run: goreleaser release --rm-dist

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: dist/
